### ISSUE TITLE
About show_result_meshlab ?

### ISSUE THREAD

**Issue by xinghuokang** [cheng052/BRNet#3]
Hi, Cheng
I have read source code, but I can not get below result in your README.md.
![微信截图_20210522151009](https://user-images.githubusercontent.com/30923040/119217954-4bc4ed80-bb10-11eb-8e47-c13433861f3b.png)

But, when I run on my machine, i got below result. 
All the detect bboxes are green, why? Abviously, there are two object(table and chair).
![微信截图_20210522151455](https://user-images.githubusercontent.com/30923040/119218037-b24a0b80-bb10-11eb-89fb-bd0eeef2e750.png)
Look forward your reply, thanks!

**Comment by cheng052** [comment]
Thanks for your interest in our work.
we produce the visualization results by manually setting the bounding box color in meshlab according to the color bar.

**Comment by xinghuokang** [comment]
Thanks for your reply,
Normally, object detections should give bbox axis and its classify, why not figure them by their classify results?

**Comment by xinghuokang** [comment]
Hi, 
In the demo/pcd_demo.py, and in inference.py, I can not find 3D NMS process?

**Comment by cheng052** [comment]
Hi,
the NMS process is done here
https://github.com/cheng052/BRNet/blob/4f9cf72f49757b8fb74e7eae50cd2c4ea3cb7f83/mmdet3d/models/roi_heads/bbox_heads/br_bbox_head.py#L112
called by inference_detector() in pcd_demo.py
The NMS is done in the model forward pass in test mode

**Comment by xinghuokang** [comment]
Firstly, thanks for your reply.
Hi, I have some questions here, 
I run the demo "CUDA_VISIBLE_DEVICES=0 python demo/pcd_demo.py demo/sunrgbd_000017.bin demo/brnet_8x1_sunrgbd-3d-10class.py checkpoints/brnet_8x1_sunrgbd-3d-10class_trained.pth", I also print the config information as below:

![微信截图_20210524110452](https://user-images.githubusercontent.com/30923040/119290831-e8f26400-bc7f-11eb-82aa-6dc22d9ba2d2.png)

- In the print config, use_nms=False(the small red box in the picture), why(I do not modify anycode)?
- can you explain the result(the big red box in the picture), "3d_box", why print so much lines?

![微信截图_20210524103554](https://user-images.githubusercontent.com/30923040/119290940-248d2e00-bc80-11eb-83de-c15d1ddae4c6.png)
![微信截图_20210524103700](https://user-images.githubusercontent.com/30923040/119290948-2820b500-bc80-11eb-8da4-8b66f7550d49.png)

Everytime, I run pcd_demo.py, it gives different results, what's wrong with it?

**Comment by cheng052** [comment]
- In the print config, use_nms=False(the small red box in the picture), why(I do not modify any code)?
This setting is in rpn (region proposal network), the nms process is done after the rcnn network.

- can you explain the result(the big red box in the picture), "3d_box", why print so many lines?
This is related to the setting per_class_proposal=True in rcnn config, you can check the appendix in VoteNet paper for details

- Every time, I run pcd_demo.py, it gives different results, what's wrong with it?
The detector suffers from some randomness. 
For example, the number of points for the network input in the SUN RGB-D dataset is set to be 20000, but the number of points in the raw point cloud is more than 20000. Thus a random sample should be done before feeding the points into the network, the random sample process can bring randomness to the detection results. 
It is a common problem in the related work, as in VoteNet, H3DNet ...

**Comment by xinghuokang** [comment]
Hi, Cheng, Thank you very much!
I need to read paper in details, then study the code. 
In your opinion, what's the current research status of 3d object detection on point cloud or 3D sementic segmentation? @cheng052

**Comment by cheng052** [comment]
- About the current research status of 3d object detection on point cloud or 3D semantic segmentation
the research focusing on 3d object detection for the outdoor environment is very active and useful for autonomous driving.
Due to the dataset limitation(indoor data is quite little compared with the outdoor counterpart), 3d object detection for the indoor environment is not that attractive but is a good way to get hands-on 3d object detection.

As for the 3D semantic segmentation task, most of the works are done on the indoor dataset(ScanNet and so on), and the 3D semantic segmentation for the outdoor environment is still worth working on.

Also, you can pay attention to many related topics about 3d detection, such as efficiency optimization, domain adaptation, semi-supervised ...
There are many other interesting topics besides getting better performance on a specific dataset.

**Comment by xinghuokang** [comment]
Thank you for your sharing, I've learned.

**Comment by xinghuokang** [comment]
![office](https://user-images.githubusercontent.com/30923040/119755690-fe140080-bed4-11eb-9ca7-44ea25bae2b8.png)
Hi，there are so many detect bbox, Is there any way to get rid of it.

**Comment by cheng052** [comment]
You can try to use a larger confidence threshold(such as 0.5) and a larger NMS threshold

**Comment by xinghuokang** [comment]
OK，I will try it. 
![image](https://user-images.githubusercontent.com/30923040/119970342-2f2e2700-bfe2-11eb-9b11-69cdf88862fa.png)

When I prepare the code, l,w,h not time to 2. But, BRNet predicts result is time to 2 compared with labels, Why?
![image](https://user-images.githubusercontent.com/30923040/119970746-b24f7d00-bfe2-11eb-9833-8067b8b6da29.png)
The above predict result is 000002 sample, its label is below,  It looks exactly 2 times to label (in l,w,h).
![image](https://user-images.githubusercontent.com/30923040/119970875-da3ee080-bfe2-11eb-961a-08023a123539.png)
